### ISSUE TITLE
Low quality Lain

### ISSUE THREAD

**Issue by itzyboi** [Damp-Cuttlefish/GDPClient#2]
Please improve the quality of your lain, it's pretty horrible to look at every time i log in and try to do something

**Comment by Damp-Cuttlefish** [comment]
This lain is part of my identity and I won't have you slandering it. Issue marked as invalid, working as intended.

**Comment by itzyboi** [comment]
@FriarOmelette please back me up here, he won't listen to me

**Comment by Damp-Cuttlefish** [comment]
It's not a bug, it's a feature.
